GET http://localhost:4000/films
Accept: application/json

###
POST http://localhost:4000/films
Content-Type: application/json

{
  "name": "Tesssdfdatdafsdsdcc Ficlsm",
  "description": "True story of Heinrich Harrer, an Austrian mountain climber who became friends with the Dalai Lama at the time of China's takeover of Tibet.",
  "date": "Invalid Date",
  "genre": "Crime",
  "released": 2008,
  "rating": 5,
  "previewVideoLink": "https://9.react.pages.academy/static/film/video/dog.mp4",
  "videoLink": "https://9.react.pages.academy/static/film/video/matrix.mp4",
  "starring": "Bradley Cooper,Sam Elliott,Tilda Swinton,John C. Reilly,Ezra Miller,Owen Wilson,Adrien Brody,Jason Schwartzman",
  "director": "Wes Anderson",
  "runTime": 75,
  "comments": 132,
  "user": "62bd52ad4edea2aa032f326f",
  "posterImage": "https://9.react.pages.academy/static/film/poster/Seven_Years_in_Tibet.jpg",
  "backgroundImage": "https://9.react.pages.academy/static/film/background/Pulp_Fiction.jpg",
  "backgroundColor": "#AD9F8B"
}

###

PUT http://localhost:4000/films/62bd6528cf1e31ad421e787a
Content-Type: application/json

{
  "name": "Updated",
  "description": "True story of Heinrich Harrer, an Austrian mountain climber who became friends with the Dalai Lama at the time of China's takeover of Tibet.",
  "date": "Invalid Date",
  "genre": "Crime",
  "released": 2008,
  "rating": 5,
  "previewVideoLink": "https://9.react.pages.academy/static/film/video/dog.mp4",
  "videoLink": "https://9.react.pages.academy/static/film/video/matrix.mp4",
  "starring": "Bradley Cooper,Sam Elliott,Tilda Swinton,John C. Reilly,Ezra Miller,Owen Wilson,Adrien Brody,Jason Schwartzman",
  "director": "Wes Anderson",
  "runTime": 75,
  "comments": 132,
  "user": "62bd1b49a4b8cc352deb7ed1",
  "posterImage": "https://9.react.pages.academy/static/film/poster/Seven_Years_in_Tibet.jpg",
  "backgroundImage": "https://9.react.pages.academy/static/film/background/Pulp_Fiction.jpg",
  "backgroundColor": "#AD9F8B"
}

###

GET http://localhost:4000/films/62bd6528cf1e31ad421e787a
Accept: application/json

###

DELETE http://localhost:4000/films/62bd6528cf1e31ad421e787a
Accept: application/json

###

GET http://localhost:4000/films/genre/Crime
Accept: application/json
